from utils import People as p


votes = {
    p.Annabel.value.name: p.Annabel,
    p.Ben.value.name: p.Ben,
    p.Elliott.value.name: p.Elliott,
    p.Euthyme.value.name: p.Euthyme,
    p.Gabby.value.name: p.Gabby,
    p.Gary.value.name: p.Gary,
    p.Gazell.value.name: p.Gazell,
    p.James.value.name: p.James,
    p.Jegor.value.name: p.Jegor,
    p.Jesse.value.name: p.Jesse,
    p.Jessica.value.name: p.Jessica,
    p.Joel.value.name: p.Joel,
    p.Joey.value.name: p.Joey,
    p.Julian.value.name: p.Julian,
    p.Kay.value.name: p.Kay,
    p.Katie.value.name: p.Katie,
    p.Lewis.value.name: p.Lewis,
    p.Mark.value.name: p.Mark,
    p.Matt.value.name: p.Matt,
    p.Molly.value.name: p.Molly,
    p.Nic.value.name: p.Nic,
    p.Phoebe.value.name: p.Phoebe,
    p.Sam.value.name: p.Sam,
    p.Samantha.value.name: p.Samantha,
    p.Sophie.value.name: p.Sophie,
    p.Will.value.name: p.Will,
}