from utils import People as p


votes = {
    p.Annabel.value.name: p.Will,
    p.Ben.value.name: p.Julian,
    p.Euthyme.value.name: p.Annabel,
    p.Gabby.value.name: p.Nic,
    # p.Gary.value.name: p.Gary,
    p.Gazell.value.name: p.Julian,
    p.James.value.name: p.Julian,
    p.Jegor.value.name: p.Katie,
    p.Jesse.value.name: p.Lewis,
    p.Jess.value.name: p.Ben,
    p.Joel.value.name: p.Lewis,
    p.Joey.value.name: p.James,
    p.Julian.value.name: p.Lewis,
    p.Kay.value.name: p.James,
    p.Katie.value.name: p.Jess,
    p.Lewis.value.name: p.Julian,
    p.Mark.value.name: p.Matt,
    p.Matt.value.name: p.Phoebe,
    # p.Molly.value.name: p.Molly,
    p.Nic.value.name: p.Julian,
    p.Phoebe.value.name: p.Lewis,
    # p.Sam.value.name: p.Sam,
    p.Samantha.value.name: p.Joey,
    p.Sophie.value.name: p.Gazell,
    p.Will.value.name: p.Katie,
}