from utils import People as p


votes = {
    p.Annabel.value.name: p.James,
    p.Ben.value.name: p.Matt,
    p.Euthyme.value.name: p.Joel,
    p.Gabby.value.name: p.Joel,
    # p.Gary.value.name: pp,
    p.Gazell.value.name: p.Joel,
    p.James.value.name: p.Matt,
    p.Jegor.value.name: p.Joel,
    p.Jesse.value.name: p.Joel,
    p.Jess.value.name: p.Nic,
    p.Joel.value.name: p.Joel,
    p.Joey.value.name: p.Joel,
    # p.Julian.value.name: p.Julian,
    p.Kay.value.name: p.Joel,
    p.Katie.value.name: p.Katie,
    p.Lewis.value.name: p.Joel,
    p.Mark.value.name: p.James,
    p.Molly.value.name: p.Joel,
    p.Matt.value.name: p.Joel,
    # p.Molly.value.name: pp,
    p.Nic.value.name: p.Joel,
    p.Phoebe.value.name: p.Lewis,
    # p.Sam.value.name: pp,
    p.Samantha.value.name: p.Samantha,
    p.Sophie.value.name: p.James,
    p.Will.value.name: p.Joel,
}